@startuml

title __HELPER's Class Diagram__\n

  package  {
    package hesge.legrand.tb.chatbot {
      package hesge.legrand.tb.chatbot.helper {
        class Constants {
            {static} + CATEGORIES_ID : String
            {static} + CONCEPTS_ID : String
            {static} + DATA_SEPARATOR : String
            {static} + ACTION_FILTER_QUESTIONS : String
            {static} + ACTION_FILTER_QUESTIONS_PARAMETER : String
            {static} + ACTION_HELP_QUESTION : String
            {static} + ACTION_END_QUESTIONS : String
            {static} + ACTION_END_CONVERSATION : String
            {static} + CHATBOT_TALK : String
            {static} + USER_TALK : String
            {static} + CODE_QUESTIONS_END : int
            {static} + CODE_QUESTIONS_PROCEED : int
            {static} + CODE_QUESTIONS_HELP : int
            {static} + UNGRADABLE_ANSWER_LIMIT : double
            {static} + PERFECT_ANSWER_LIMIT : double
            {static} + GOOD_ANSWER_LIMIT : double
            {static} + ACCEPTABLE_ANSWER_LIMIT : double
            {static} + FEEDBACK_PERFECT_ANSWER : String
            {static} + FEEDBACK_GOOD_ANSWER : String
            {static} + FEEDBACK_ACCEPTABLE_ANSWER : String
            {static} + FEEDBACK_BAD_ANSWER : String
            {static} + FEEDBACK_UNGRADABLE : String
            {static} + FEEDBACK_ANSWER_NOT_VALID : String
        }
      }
    }
  }
  

  package  {
    package hesge.legrand.tb.chatbot {
      package hesge.legrand.tb.chatbot.helper {
        class Credentials {
            {static} + NLU_APIKEY : String
            {static} + NLU_API_URL : String
            {static} + NLU_VERSION : String
            {static} + ASSISTANT_ID : String
            {static} + ASSISTANT_APIKEY : String
            {static} + ASSISTANT_API_URL : String
            {static} + ASSISTANT_VERSION : String
            {static} - WORKSPACE_ID : String
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
